//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TableTennisSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Serve
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Serve;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slowmo
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Slowmo;
            }
        }
        
        public virtual SteamVR_Action_Boolean Up
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean Down
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Down;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Right;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose2
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Pose2;
            }
        }
        
        public virtual SteamVR_Action_Pose ControllerPose
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_ControllerPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Ghost
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Ghost;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.tableTennisSet_Haptic;
            }
        }
    }
}
